# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b60e8263c5c74c4faa854561716de39ee27f7748ccbb1e44ed64c45fa1adb48c314db69e50d806f27552f6d614011205acb8a633efe6bf010349a1ba50994e6e

test:
  secret_key_base: bf4847ee6a8466a23ca7d24bd86c18ef69f5dfd034b60ac52e7735d3aa797e85e6e75c557d25782e105e1e1a3bbea5a24b9bae40e891b572febf280870506e1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
